version: '3'

services:

  webapi:
    restart: always
    build: 
      context: .
      dockerfile: docker/webapi/Dockerfile
    volumes:
      - .:/opt/services/webapi
      - static_volume:/opt/static
    networks:
      - nginx_network
      - db_network
    env_file:
      - docker/webapi/webapi_env
    depends_on:
      - db
  
  nginx:
    restart: always
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - static_volume:/opt/static
    depends_on:
      - webapi
    networks:
      - nginx_network

  db:
    restart: always
    image: postgres
    env_file:
      - docker/db/db_env
    networks:
      - db_network
      - todb  # DEBUG
    ports:
     - 5432:5432  # DEBUG
    volumes:
      - db_volume:/var/lib/postgresql/data

  DEBUG
  adminer:
    restart: always
    image: dpage/pgadmin4
    networks:
      - todb
    ports:
      - 8090:8010
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "angryshikamaru@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "gif54TRU"
      PGADMIN_LISTEN_PORT: "8010"

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
  todb:  # DEBUG
    driver: bridge  # DEBUG

volumes:
  db_volume:
  static_volume:
